# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/miuicamera-sm8250/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/miuicamera-sm8250

PRODUCT_PACKAGES += \
    MiuiCamera \
    MiuiScanner \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libgui-xiaomi \
    libmicampostproc_client \
    vendor.xiaomi.hardware.campostproc@1.0_system
